import { LoveQuestion } from "./love-types";

export const loveQuestions: LoveQuestion[] = [
  {
    id: 1,
    type: "binary",
    text: "When you're falling for someone—",
    left: "You think about them constantly. Everything reminds you of them.",
    right: "You notice the feeling but keep living your life as normal.",
  },
  {
    id: 2,
    type: "bare",
    text: "The person you like just cancelled your plans. You—",
    options: {
      A: "Send a message saying you're disappointed.",
      B: "Say it's fine and mean it.",
      C: "Say it's fine and don't mean it.",
      D: "Make a joke to hide that you care.",
    },
  },
  {
    id: 3,
    type: "bare",
    text: "You've been seeing someone for a month. You haven't heard from them in two days. You—",
    options: {
      A: "Send a casual message, no big deal.",
      B: "Notice the silence but wait it out.",
      C: "Feel anxious, check your phone more than usual.",
      D: "Appreciate the space honestly.",
    },
  },
  {
    id: 4,
    type: "slider",
    text: "In a relationship, how much of your life do you want to share?",
    sliderLeft: "I keep most things to myself.",
    sliderRight: "We share everything. No walls.",
  },
  {
    id: 5,
    type: "binary",
    text: "When you love someone—",
    left: "You say it often. You want them to feel it constantly.",
    right: "You show it through what you do. Words feel insufficient.",
  },
  {
    id: 6,
    type: "bare",
    text: "What scares you most in love?",
    options: {
      A: "Being too much for someone.",
      B: "Not being enough for someone.",
      C: "Losing yourself in someone.",
      D: "Never fully letting someone in.",
    },
  },
  {
    id: 7,
    type: "slider",
    text: "How do you make decisions in relationships?",
    sliderLeft: "I follow my heart. If it feels right I trust it.",
    sliderRight: "I think it through carefully before I commit to anything.",
  },
  {
    id: 8,
    type: "bare",
    text: "Your partner seems distant lately but says everything is fine. You—",
    options: {
      A: "Take them at their word and give them space.",
      B: "Keep checking in — 'fine' never means fine.",
      C: "Pull back yourself, match their energy.",
      D: "Bring it up directly — you need to know what's actually happening.",
    },
  },
  {
    id: 9,
    type: "bare",
    text: "When you're upset with someone you love, you—",
    options: {
      A: "Tell them immediately. You can't pretend.",
      B: "Wait until you've processed it yourself first.",
      C: "Drop hints and hope they notice.",
      D: "Go quiet and need them to ask.",
    },
  },
  {
    id: 10,
    type: "binary",
    text: "Love is—",
    left: "The most important thing. You'd rearrange your life for the right person.",
    right: "Important, but not everything. You need more than love to build a life.",
  },
  {
    id: 11,
    type: "slider",
    text: "How quickly do you let someone in?",
    sliderLeft: "Slowly. Trust is earned over time. Walls come down gradually.",
    sliderRight: "Quickly. If the feeling is there I dive in.",
  },
  {
    id: 12,
    type: "bare",
    text: "In your ideal relationship, you and your partner—",
    options: {
      A: "Have your own separate worlds that occasionally overlap.",
      B: "Share everything — same friends, same plans, same life.",
      C: "Are deeply connected but fiercely independent.",
      D: "Are each other's whole world. That's the point.",
    },
  },
  {
    id: 13,
    type: "pill",
    text: "You've been feeling disconnected from your partner lately. How do you handle it?",
    options: {
      A: "You bring it up directly — 'I feel like we've been distant'",
      B: "You plan something intentional to reconnect without saying why",
      C: "You wait and see if it passes on its own",
      D: "You pull back slightly and see if they notice and reach out",
    },
  },
  {
    id: 14,
    type: "bare",
    text: "Your definition of a good relationship is one that—",
    options: {
      A: "Feels electric. There's always tension, passion, aliveness.",
      B: "Feels safe. You know exactly where you stand.",
      C: "Grows you. You become a better person inside it.",
      D: "Lasts. Longevity is the only real measure.",
    },
  },
  {
    id: 15,
    type: "binary",
    text: "In love you are more—",
    left: "The one who loves a little harder. Gives a little more. Always.",
    right: "The one who holds back just enough. Protection is instinct.",
  },
  {
    id: 16,
    type: "slider",
    text: "How much space do you need in a relationship?",
    sliderLeft: "A lot. Time alone recharges me. My independence is non-negotiable.",
    sliderRight: "Very little. I want to be around them as much as possible.",
  },
  {
    id: 17,
    type: "binary",
    text: "When something is wrong between you and someone you love—",
    left: "You address it directly. Clarity matters more than comfort.",
    right: "You let it settle. You don't want to create conflict over something that might pass.",
  },
  {
    id: 18,
    type: "bare",
    text: "When a relationship starts feeling really serious, your instinct is—",
    options: {
      A: "To lean in. This is what you wanted.",
      B: "To feel a flutter of panic then settle into it.",
      C: "To suddenly need more space than before.",
      D: "To feel grateful and calm. You trust this.",
    },
  },
  {
    id: 19,
    type: "bare",
    text: "The people who have loved you would say you—",
    options: {
      A: "Love deeply but are hard to fully reach.",
      B: "Give more than you receive and don't always notice.",
      C: "Make love feel like an adventure.",
      D: "Make people feel safe in a way they can't explain.",
    },
  },
  {
    id: 20,
    type: "bare",
    text: "After an argument with someone you love, you—",
    options: {
      A: "Need to resolve it immediately, the tension is unbearable.",
      B: "Take space first, come back when you've processed.",
      C: "Apologise quickly even if you weren't wrong — peace matters more.",
      D: "Talk it through calmly when you're both ready.",
    },
  },
  {
    id: 21,
    type: "slider",
    text: "How openly do you express love?",
    sliderLeft: "Very privately. What I feel stays between us or inside me.",
    sliderRight: "Very openly. I say it, show it, and want them to know always.",
  },
  {
    id: 22,
    type: "bare",
    text: "When you imagine a future with someone you love, you think about—",
    options: {
      A: "How it feels. The warmth of building something together.",
      B: "Whether it makes practical sense. Life is more than feeling.",
      C: "Whether you'll still want each other in ten years.",
      D: "Whether they make you want to be better.",
    },
  },
  {
    id: 23,
    type: "binary",
    text: "In love, your instinct is to—",
    left: "Protect yourself first. You've learned that openness has a cost.",
    right: "Give fully first. You'd rather love completely and risk it than hold back.",
  },
  {
    id: 24,
    type: "bare",
    text: "At the end of a relationship, what stays with you longest?",
    options: {
      A: "The moments of closeness you can't recreate with anyone else.",
      B: "The version of yourself you were when you were with them.",
      C: "The things you wish you'd said.",
      D: "The relief of having your own life back.",
    },
  },
];
