import { Question } from "./types";

export const questions: Question[] = [
  {
    id: 1,
    tag: "A",
    type: "Scenario",
    text: "Your team just hit a major roadblock. Your instinct is to:",
    options: {
      A: "Step back and rethink the whole direction",
      B: "Rally everyone and rebuild momentum together",
      C: "Identify the exact blocker and fix it yourself",
      D: "Find who's best placed to solve it and remove their obstacles",
    },
    format: "binary",
    binaryLeft: "A",
    binaryRight: "C",
  },
  {
    id: 2,
    tag: "P",
    type: "Word association",
    text: "Pick the word that feels most like you:",
    options: {
      A: "Sharp",
      B: "Warm",
      C: "Steady",
      D: "Electric",
    },
    format: "pill",
  },
  {
    id: 3,
    tag: "A",
    type: "Preference",
    text: "Which feels more satisfying?",
    options: {
      A: "Coming up with the idea",
      B: "Seeing the idea become reality",
      C: "Getting the whole team aligned on the idea",
      D: "Finding a faster way to execute the idea",
    },
    format: "binary",
    binaryLeft: "A",
    binaryRight: "B",
  },
  {
    id: 4,
    tag: "P",
    type: "Reflective",
    text: "The people who know you best would say you're someone who:",
    options: {
      A: "Always finds a way, no matter what",
      B: "Doesn't need to say much but always delivers",
      C: "Makes everyone around them better",
      D: "Changes the energy of a room just by being in it",
    },
    format: "pill",
  },
  {
    id: 5,
    tag: "A",
    type: "Instinct",
    text: "You're handed a completely blank canvas at work. Your first reaction is:",
    options: {
      A: "Excitement — finally, no constraints",
      B: "Curiosity — what do other people need from this",
      C: "Focus — what's the fastest path to something concrete",
      D: "Strategy — who should I bring in to make this great",
    },
    format: "bare",
  },
  {
    id: 6,
    tag: "P",
    type: "Preference",
    text: "When you're at your best, you're usually:",
    options: {
      A: "Locked in, completely in the zone, unstoppable",
      B: "So deep in thought nobody realises what's coming",
      C: "Out front, setting the pace, pulling people with you",
      D: "The calmest person in a chaotic situation",
    },
    format: "slider",
  },
  {
    id: 7,
    tag: "A",
    type: "Word association",
    text: "Which word excites you most?",
    options: {
      A: "Vision",
      B: "Impact",
      C: "Systems",
      D: "People",
    },
    format: "binary",
    binaryLeft: "A",
    binaryRight: "C",
  },
  {
    id: 8,
    tag: "P",
    type: "Reflective",
    text: "If a colleague had to describe how you show up to work in one sentence, they'd say:",
    options: {
      A: '"They just get things done, I don\'t know how"',
      B: '"You never really see them coming until they\'ve already won"',
      C: '"They make you want to work harder just by being around"',
      D: '"Nothing seems to shake them"',
    },
    format: "bare",
  },
  {
    id: 9,
    tag: "A",
    type: "Scenario",
    text: "You're given a high stakes project with no clear brief. You:",
    options: {
      A: "Start by defining what success looks like in 12 months",
      B: "Get the right people in a room and figure it out together",
      C: "Break it into steps and start on the first one immediately",
      D: "Map out who owns what and make sure everyone's unblocked",
    },
    format: "pill",
  },
  {
    id: 10,
    tag: "P",
    type: "Instinct",
    text: "When something goes wrong, your gut reaction is to:",
    options: {
      A: "Fix it immediately, whatever it takes",
      B: "Take a breath, assess quietly, then move",
      C: "Gather people and address it head on",
      D: "Stay calm and be the stability others need",
    },
    format: "binary",
    binaryLeft: "A",
    binaryRight: "D",
  },
  {
    id: 11,
    tag: "A",
    type: "Preference",
    text: "Which role would you naturally gravitate toward in a startup?",
    options: {
      A: "The one with the big picture vision, setting direction",
      B: "The one building the product, making it real",
      C: "The one connecting everyone, keeping culture alive",
      D: "The one in the market, understanding what people actually need",
    },
    format: "bare",
  },
  {
    id: 12,
    tag: "P",
    type: "Word association",
    text: "Pick the combination that feels most like you at work:",
    options: {
      A: "Fast and focused",
      B: "Deep and deliberate",
      C: "Loud and energising",
      D: "Calm and unshakeable",
    },
    format: "slider",
  },
  {
    id: 13,
    tag: "A",
    type: "Reflective",
    text: "Your most natural contribution to any team is:",
    options: {
      A: "Seeing where things should go before anyone else does",
      B: "Doing the work that actually moves things forward",
      C: "Making sure everyone is aligned and nobody is lost",
      D: "Challenging assumptions and pushing the team to think differently",
    },
    format: "bare",
  },
  {
    id: 14,
    tag: "P",
    type: "Scenario",
    text: "You're in a high pressure meeting and things start getting tense. You:",
    options: {
      A: "Take control and push through to a decision",
      B: "Stay quiet, observe, then say the one thing that cuts through",
      C: "Inject energy and reframe the situation positively",
      D: "Slow things down and bring the room back to earth",
    },
    format: "binary",
    binaryLeft: "A",
    binaryRight: "D",
  },
  {
    id: 15,
    tag: "A",
    type: "Instinct",
    text: "When you imagine your ideal work day, it looks like:",
    options: {
      A: "Deep thinking, big ideas, mapping out what's possible",
      B: "Head down, making tangible progress on something real",
      C: "Collaborating, energy bouncing between you and others",
      D: "Running a tight process, watching everything come together",
    },
    format: "slider",
  },
  {
    id: 16,
    tag: "P",
    type: "Preference",
    text: "Which of these feels most like a compliment to you?",
    options: {
      A: '"You\'re one of the hardest working people I know"',
      B: '"There\'s something about you that\'s hard to read but impossible to ignore"',
      C: '"You just have this energy that pulls people in"',
      D: '"You never panic. Ever."',
    },
    format: "bare",
  },
  {
    id: 17,
    tag: "A",
    type: "Scenario",
    text: "Your company is about to make a decision you think is wrong. You:",
    options: {
      A: "Make the case for a different direction with data and vision",
      B: "Rally the people around you who feel the same way",
      C: "Find the fastest way to course correct within existing constraints",
      D: "Quietly work around it and deliver results that speak for themselves",
    },
    format: "pill",
  },
  {
    id: 18,
    tag: "I",
    type: "Industry",
    text: "Which of these work environments sounds most like where you'd thrive?",
    options: {
      A: "Fast moving, high growth, building something from scratch",
      B: "Established but evolving, room to make a real mark",
      C: "People focused, mission driven, impact over profit",
      D: "Analytical, rigorous, high standards and high stakes",
    },
    format: "pill",
  },
  {
    id: 19,
    tag: "I",
    type: "Industry",
    text: "What does success look like to you in 10 years?",
    options: {
      A: "Built something that didn't exist before",
      B: "Known as the best in your field",
      C: "Led a team that genuinely loves working together",
      D: "Solved a problem that actually matters at scale",
    },
    format: "bare",
  },
  {
    id: 20,
    tag: "P",
    type: "Reflective",
    text: "At the end of a really good week at work, what made it good?",
    options: {
      A: "You moved fast and got more done than anyone expected",
      B: "You did quiet, important work that will matter later",
      C: "You brought people together and the energy was electric",
      D: "You were the rock — steady, reliable, exactly what was needed",
    },
    format: "binary",
    binaryLeft: "A",
    binaryRight: "D",
  },
];
